version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
